---
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-ingress-configuration
data:
  haproxy.cfg: |-
    defaults
      # never fail on address resolution
      default-server init-addr none
    # healthz
    frontend healthz
      mode http
      monitor-uri /healthz
      bind *:80
      timeout connect 5000ms
      timeout client 50000ms
      timeout server 50000ms
