---
apiVersion: networkingress.little-angry-clouds.k8s.io/v1
kind: NetworkIngress
metadata:
  name: networkingress-sample-1
spec:
  rules:
    - host: mongo.db.com
      port: 27017
      targetPort: 27017
      name: mongo
---
apiVersion: networkingress.little-angry-clouds.k8s.io/v1
kind: NetworkIngress
metadata:
  name: networkingress-sample-2
spec:
  rules:
    - host: mysql.db.com
      port: 3306
      targetPort: 3306
      name: mysql
