---
apiVersion: little-angry-clouds.k8s.io/v1
kind: NetworkIngress
metadata:
  name: networkingress-sample-1
  labels:
    kubernetes.io/network-ingress.class: haproxy
spec:
  rules:
    - host: mongo.db.com
      port: 27017
      targetPort: 27017
      name: mongo
---
apiVersion: little-angry-clouds.k8s.io/v1
kind: NetworkIngress
metadata:
  name: networkingress-sample-2
spec:
  rules:
    - host: mysql.db.com
      port: 3306
      targetPort: 3306
      name: mysql
---
# This shouldn't be reconcilied by the default class
apiVersion: little-angry-clouds.k8s.io/v1
kind: NetworkIngress
metadata:
  name: networkingress-sample-3
  labels:
    kubernetes.io/network-ingress.class: haproxy2
spec:
  rules:
    - host: google.com
      port: 443
      targetPort: 443
      name: google
